AKENEO_BASE_URL = "https://pimbl.mhost.eu/api/rest/v1"
AKENEO_CLIENT_ID = "28_4zr48a3eq7sw0wwccsss4w8sso088k4swkcookg8wocss4gskg"
AKENEO_SECRET = "5wgc0231b8kkkc40oww8ss0kcs84sowc0ws4w4g084gwog4c8c"
AKENEO_USERNAME = "marcincontentgenerator_3621"
AKENEO_PASSWORD = "263e7888c"
GOOGLE_API_KEY = "AIzaSyAl69MEfwxVIiU7sX6M3u-KOqVI_c782Yc"
AKENEO_PROXY = ""
